name: neural_network
channels:
  - conda-forge
  - defaults
  - apple
dependencies:
  - python=3.10
  - pandas
  - tensorflow>=2.13
  - scikit-learn
  - ipykernel
  - pip
  - pip:
      - tensorflow-macos
      - tensorflow-metal
